// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiHomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Home';
};

export type GetApiHomeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiHomeResponse = GetApiHomeResponses[keyof GetApiHomeResponses];
